language: ruby
rvm:
  - "2.1.3"
env:
  - DB=postgresql

script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

before_script:
  - cp config/database.travis.yml config/database.yml

bundler_args: --binstubs=./bundler_stubs
 
