language: ruby

rvm:
 — 2.5.0

script:
  - bundle -v
  - bundle install — jobs=3 — retry=3
  - bundle exec rake bin/rails db:create
  - bundle exec rake bin/rails db:migrate
  - bundle exec rspec

before_script:
  - cp config/database.yml


 

